### ISSUE TITLE
The package' react-native-fast-tflite' doesn't seem to be linked.

### ISSUE THREAD

**Issue by patras1** [mrousavy/react-native-fast-tflite#1]
I'm getting this error:
![IMG_FD12E22A28B4-1](https://github.com/mrousavy/react-native-fast-tflite/assets/27278294/cdaa5c56-c922-43f4-af89-cf406699d014)

1. I did run 'pod install'
2. I did rebuild the app.
3. I'm not using Expo Go

Any advice?
Thank

**Comment by mrousavy** [comment]
Huh, weird. I don't know what's going on there, can you run `npx react-native info`?

**Comment by patras1** [comment]
There you go:

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 7.27 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/danpatra/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
