### ISSUE TITLE
Error loading local .tflite model in Android release build when Expo Updates are enabled.

### ISSUE THREAD

**Issue by joonshakya** [mrousavy/react-native-fast-tflite#104]
I noticed that ze release build didn't load ze model correctly in Android when loading models using
```tsx
  const model = useTensorflowModel(
    require("../assets/ai-models/ze-most-amazing-model.tflite"),
  );
```

I created a minimal project using just `react-native-fast-tflite` and ze release builds were working fine. So to check what's causing ze error, I kept on rebuilding ze release app adding one dependency at a time.
After 2 days I came to ze conclusion that something in expo updates is causing ze Android release build to have error loading ze local model.

My `app.json`
```json
{
  "expo": {
    ...,
    "extra": {
      "eas": {
        "projectId": "my-real-project-id"
      }
    },
    "updates": {
      "url": "https://u.expo.dev/my-real-project-id"
    },
    "plugins": [
      "expo-router",
      [
        "react-native-vision-camera",
        {
          "cameraPermissionText": "$(PRODUCT_NAME) needs access to your Camera.",
          "enableMicrophonePermission": true,
          "microphonePermissionText": "$(PRODUCT_NAME) needs access to your Microphone."
        }
      ],
      [
        "react-native-fast-tflite"
      ],
      [
        "expo-updates",
        {
          "username": "my-username"
        }
      ],
    ]
  }
}
```

After removing ze `expo.updates` property from `app.json`, I was able to get ze model loading properly in ze release build but expo updates may not work using this workaround.
Is there any way to have ze local model load fine along with expo-updates in android release builds?

**Comment by joonshakya** [comment]
Hi @mrousavy,
Could you please take a look at this issue, do let me know if I would need to provide mode information.

**Comment by mrousavy** [comment]
hey - hm not sure, file should be supported as of the latest version

**Comment by mrousavy** [comment]
actually maybe i forgot something - try again with 1.5.0 i just released it
