### ISSUE TITLE
Problems and confusion regarding the input format

### ISSUE THREAD

**Issue by c-goettert** [mrousavy/react-native-fast-tflite#11]
First of all, many thanks for this library. It looks really promising to me, but I struggle to get it working correctly. In a first step, I wanted to test the library without a camera, using just a local image.  I managed to get an output, but my problem is that it doesn't seem to be accurate. I use the [object detection example](https://www.tensorflow.org/lite/examples/object_detection/overview) from the Tensorfow website as my model. Based on [netron.app](https://netron.app/) I can tell that the input tensor of the model is shaped as follows:  uint8[1,300,300,3].

My first hurdle was to get my local image into the desired _ArrayBuffers_ format, taking into account the expected input format of the model. I endet up using the _Image_ object from [react-native-skia](https://github.com/Shopify/react-native-skia). I draw my testimage onto a 300x300 pixel canvas to extract the pixels and convert them to the desired data-shape using the following code:

```
    ...
    const imageBytes = image.readPixels()
    const rgbData = new Uint8Array(300 * 300 * 3)

    // Input shape: 1 uint8[1,300,300,3]
    // Meaning: 300 x 300 Pixels + 3 bit for RGB
    // Copy pixel but leave out alpha channel
    for (let i = 0, j = 0; i < imageBytes.length; i += 4, j += 3) {
      rgbData[j] = imageBytes[i] // Red
      rgbData[j + 1] = imageBytes[i + 1] // Green
      rgbData[j + 2] = imageBytes[i + 2] // Blue
    }

    const dataArray = await model.model.run([rgbData])

    const locations = dataArray[0]
    const classes = dataArray[1]
    const scores = dataArray[2]

    const topDetections = []

    for (let i = 0; i < Math.min(classes.length, 3); i++) {
      topDetections.push({
        location: locations[i],
        score: scores[i],
        class: labelmap[classes[i]]
      })
    }

    const output = 'Guesses:\n' + topDetections.map((detection) => `${detection.class} (${detection.score})\n`)
    setGuess(output)
```
First I was a bit confused, as I am passing an Uint8Array instead of an array buffer, but I was happy the model finally returned something. However, as you can see from my screenshot, the result is not as expected (there is a "cat" class in the model..).
<img width="239" alt="Bildschirmfoto 2023-11-28 um 19 20 29" src="https://github.com/mrousavy/react-native-fast-tflite/assets/7591624/7d3f1462-8c0e-4715-b3e6-e1b151aec43b">

Does anyone have any idea where my error could lie? I'm not sure what the first 1 in the input format [**1**,300,300,3] means. Somewhere I read it's called batch dimension, but I have no clue if or how to add it to my input tensor.

**Comment by mrousavy** [comment]
Hey, thanks for using the lib!

Well this varies from model to model. I think getting the input data right is the most difficult process of all, so once you got that, it's only smooth sailing from there on.

My guesses are, either the RGB data is not correct, or it is not exactly the target size, or it is BGR instead of RGB, or your `imageBytes` actually contains wrong data, etc.

The term `[1, 300, 300, 3]` means one batch of 300 width, 300 height, with 3 values per item - so yes, 300x300, RGB (or BGR). If it's a `uint8_t` model then it's 8-bit, 0-255 values.

**Comment by mashad6** [comment]
@c-goettert  greetings! can you please help me in creating input format? my model dimensions are 1*640*640*3.
Will appreciate it
thanks

**Comment by mashad6** [comment]
@c-goettert  howd you read the image pixels?
