### ISSUE TITLE
How to convert image into 4d tensor typed Array

### ISSUE THREAD

**Issue by PeterBernanth** [mrousavy/react-native-fast-tflite#24]
Hey @mrousavy ,
 
 I have been working with a model which expects input in the following format.
 - Inputs:
  - float32 serving_default_input_1:0[1,768,768,3]
  
  I have used the frame processor from react-native-vision-camera
  
```
   const frameProcessor = useFrameProcessor(
    frame => {
      'worklet';
      runAtTargetFps(1, () => {
        'worklet';
        if (actualModel == null) {
          // model is still loading...
          return;
        }
        const resized = resize(frame, {
          size: {
            width: 768,
            height: 768,
          },
          pixelFormat: 'rgb-uint8',
        });
        const result = actualModel.runSync([new Uint8Array(resized)]);
        console.log('result--->', result);
      });
    },
    [actualModel],
  );
```
  
  My model is running and giving the same output for every frame. Can you help with that ?

**Comment by mrousavy** [comment]
Well you are resizing to uint8, that's not float.

I don't have float support yet, can you reformat your model to use uint8 instead?

**Comment by mrousavy** [comment]
And 4D arrays in TFLite are simply 1D arrays with the sum of the dimensions.
