### ISSUE TITLE
Problem with loading tflite model on Android in release version

### ISSUE THREAD

**Issue by mario688** [mrousavy/react-native-fast-tflite#25]
Hi, there is an issues with the library on Android in the release version.

First:
Function **loadTensorflowModel** in TensorflowLite.ts use  
```
const asset = Image.resolveAssetSource(source)
uri = asset.uri
```
In Dev mode, assets are served from the server, so the URI will be: "http://localhost:8081/assets/src/assets/mymodel.flite?platform=android&hash=...." so it works,
but in release mode on Android, asset.uri will be: src_assets_mymodel

Second:
The function **fetchByteDataFromUrl** in lib/android in TfliteModule.java uses the HTTP request method, which throws an error because it expects the URL scheme to be "http" or "https."

```
 
  public static byte[] fetchByteDataFromUrl(String url) {
    OkHttpClient client = new OkHttpClient();

    Request request = new Request.Builder().url(url).build();

    try (Response response = client.newCall(request).execute()) {
      if (response.isSuccessful() && response.body() != null) {
        return response.body().bytes();
      } else {
        throw new RuntimeException("Response was not successful!");
      }
    } catch (Exception e) {
      Log.e(NAME, "Failed to fetch URL " + url + "!", e);
      return null;
    }
  }
```
<img width="1095" alt="Screenshot 2024-01-23 at 13 28 42" src="https://github.com/mrousavy/react-native-fast-tflite/assets/56019201/3704c12f-c85f-48a6-bbcf-30942d823e6b">

On iOS, everything works fine

**Comment by mrousavy** [comment]
Hey - ah, interesting. Well I guess this requires some fixing on the android side then to also make it work in release - if you find a fix let me know!

**Comment by mbpictures** [comment]
Hi! I stumbled in this issue as well and I used this patch to "fix" it:
```diff
void TensorflowPlugin::copyInputBuffers(jsi::Runtime& runtime, jsi::Object inputValues) {
@@ -213,9 +207,17 @@ void TensorflowPlugin::copyInputBuffers(jsi::Runtime& runtime, jsi::Object input
   }
 
   for (size_t i = 0; i < count; i++) {
-    TfLiteTensor* tensor = TfLiteInterpreterGetInputTensor(_interpreter, i);
     auto value = array.getValueAtIndex(runtime, i);
     auto inputBuffer = getTypedArray(runtime, value.asObject(runtime));
+    int inputDimensions[] = {static_cast<int>(inputBuffer.length(runtime))};
+    TfLiteInterpreterResizeInputTensor(_interpreter, i, inputDimensions, 1);
+    TfLiteStatus status = TfLiteInterpreterAllocateTensors(_interpreter);
+    if (status != kTfLiteOk) {
+      [[unlikely]];
+      throw std::runtime_error("Failed to allocate memory for input/output tensors! Status: " +
+                               tfLiteStatusToString(status));
+    }
+    TfLiteTensor* tensor = TfLiteInterpreterGetInputTensor(_interpreter, i);
     TensorHelpers::updateTensorFromJSBuffer(runtime, tensor, inputBuffer);
   }
 }
@@ -230,6 +232,7 @@ jsi::Value TensorflowPlugin::copyOutputBuffers(jsi::Runtime& runtime) {
     TensorHelpers::updateJSBufferFromTensor(runtime, *outputBuffer, outputTensor);
     result.setValueAtIndex(runtime, i, *outputBuffer);
   }
+
   return result;
 }
```

However, this fix has some drawbacks: As it reads the model outside of the android assets folder, you have to use react-native-asset to copy your tflite model to the android asset directory AND the naming of the model should be something like: "src/assets/MODEL_NAME.tflite". The resolved URL will then be "src_assets_MODEL_NAME.tflite", then the model name can be extracted correctly by the provided patch. I hope this helps anyone!

I also guess this will be an issue on iOS as well, as the passed URL is not valid? So maybe some can rewrite the data loading function of the Objective C code as well, as I have no experience in ObjectiveC.

**Comment by mrousavy** [comment]
Thanks for the patch @mbpictures - could you maybe create a PR for that?

Not sure if this can be made generic, but it also works for Images in RN so I'm not sure why it wouldnt work for such custom types.

**Comment by mrousavy** [comment]
See this PR: https://github.com/mrousavy/react-native-fast-tflite/pull/30

**Comment by AlexHird** [comment]
Still facing the same issue in latest version (1.2.0).

I initially attempted to use a require statement, when that was unsuccessful, I tried loading the asset async with `expo-assets` and pass the `file:///...` string as the key value to the url parameter. In dev mode, both attempts crashes the Android version but works fine on iOS. In release mode i get the same error as above: 

`Error: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but was 'file'`

Path during runtime (logged using datadog) was indeed valid: `file:///data/user/0/<package-name>/files/.expo-internal/8c27d0eef1a3447e68f5704859bdc418.tflite`

**Comment by joonshakya** [comment]
I was having the same issue of models not working in release builds.
I dug through files removing everything and for me I found out that expo-updates was causing some issues
I removed the `expo.updates` property from `app.json` and the model loaded fine in Android release build using the following code: 
```tsx
  const model = useTensorflowModel(
    require("../assets/ai-models/ze-most-amazing-model.tflite"),
  );
```
