### ISSUE TITLE
Problem with using GPU Delegates

### ISSUE THREAD

**Issue by Cosmorider** [mrousavy/react-native-fast-tflite#28]
I enabled the GPU Delegates in app.json, and I have $EnableCoreMLDelegate=true in my Podfile, yet when I try to load the example model in the README (using the exact same code), I get the following error:
`ERROR  Failed to load Tensorflow Model 14! [Error: Failed to create TFLite interpreter from model "http://192.168.1.79:8081/assets/assets/models/efficientdet.tflite?platform=ios&hash=8c27d0eef1a3447e68f5704859bdc418"!]`

Note that I do not get this error when I don't use 'core-ml' in `loadTensorflowModel`.

I'm using iPhone 7 Plus with iOS 14.4.2.

**Comment by mrousavy** [comment]
Yes - not every TFLite model is compatible with the CoreML GPU delegate.
Some are, some aren't.
Maybe I should've chosen a CoreML Compatible model for the example..
