### ISSUE TITLE
How to get coordinates and confidence information from yolo 8 model

### ISSUE THREAD

**Issue by MarcoHuixxx** [mrousavy/react-native-fast-tflite#46]
<img width="343" alt="螢幕截圖 2024-01-30 下午9 22 41" src="https://github.com/mrousavy/react-native-fast-tflite/assets/113924930/926fab60-41ff-4878-bd18-b3a996f6d4ba">
The above is the model properties, there should be one float32 output. However, after executing model.runSync([data]). The output is 
<img width="1174" alt="螢幕截圖 2024-01-30 下午9 22 52" src="https://github.com/mrousavy/react-native-fast-tflite/assets/113924930/b79dea00-5df1-4420-8665-17190265116f">
I have no idea about how to get the detection result from this model. Anyone can help?

**Comment by mrousavy** [comment]
Sorry but this is not really related to the issue tracker here. I don't know that model, I don't use that model, so I can't help you.

Ask in the yolo support channel

**Comment by dsshard** [comment]
I have the same question, if anyone has figured it out, please write.

**Comment by boorad** [comment]
I think it could be a thing that this library handles in the future.  I have the same issue, and found [this discussion](https://github.com/ultralytics/yolov5/issues/13396#issuecomment-2508658245) which has helped a bit, but I'm not quite there yet.

I have an output tensor `float32[1, 6, 8400]` (will scale to int after I see things working) and the code in the above discussion doesn't work.  I think the 6 means I have two labels, but I get floats for every value in the output.

**Comment by seppemp** [comment]
This is not related to this lib, it's related to Yolo as @mrousavy said. All the discussions should be done in Ultralitics.

**Comment by drewandre** [comment]
Unsure if this is helpful, but I had a lot of trouble interpreting a yolo tflite model as well, and ended up getting it to work on [this codepen](https://codepen.io/drewandre/pen/eYqNNQO). I then used this example as a guide to implementing in my react-native app.

**Comment by boorad** [comment]
> [@boorad](https://github.com/boorad) Did you get it to work? I have the same issue with a tflite model converted from a yolo12 base model. When running through fast tflite I am not getting any accurate detection or classes

No, but I did add NMS like is now possible via https://github.com/ultralytics/ultralytics/pull/18484.
