### ISSUE TITLE
How to use GPU Acceleration on Android?

### ISSUE THREAD

**Issue by tomerh2001** [mrousavy/react-native-fast-tflite#47]
The guide mentioned setting up GPU delegation for IOS, but how can I do it in Android?

**Comment by mrousavy** [comment]
As of today, there is no GPU acceleration available on Android. I didn't add it yet. If you need GPU acceleration on Android, consider contacting me through my agency [Margelo](https://margelo.io), and we can develop that feature for you 👍

**Comment by jslok** [comment]
I have tried to enable nnapi acceleration but not sure what I am missing. The below will cause the camera to show a white screen for about 20 seconds on init, then the model will fail to load. I am open to hints if you are willing to point me in the direction, Marc.

In TensorflowPlugin.cpp:

```#include <tensorflow/lite/delegates/nnapi/nnapi_delegate_c_api.h>```

```
TfLiteNnapiDelegateOptions nnapi_options = TfLiteNnapiDelegateOptionsDefault();
auto delegate = TfLiteNnapiDelegateCreate(&nnapi_options);
TfLiteInterpreterOptionsAddDelegate(options, delegate);
```

Also tried with TfLiteInterpreterOptionsSetUseNNAPI but same result.

**Comment by mrousavy** [comment]
Yea I tried that as well but didn't investigate further.
If you find something let me know!

**Comment by JEF1056** [comment]
Wrote up and tested this patch: https://github.com/mrousavy/react-native-fast-tflite/compare/main...JEF1056:react-native-fast-tflite:main

In my android logcat I can see NNAPI being initalized, and see quite a noticable perfomance improvement on models that can be GPU accelerated.

Using this change is the same as CoreML, let me know if you'd like me to make a PR for this

**Comment by mrousavy** [comment]
Yea if you can make it optional, same way as CoreML, that would be great.

Add an enum to it and i'll merge it
