### ISSUE TITLE
Error: The package 'react-native-fast-tflite' doesn't seem to be linked.

### ISSUE THREAD

**Issue by jcverah** [mrousavy/react-native-fast-tflite#53]
Hello,

I 've modify this example https://github.com/tensorflow/tfjs-examples/tree/master/react-native/image-classification/expo
in order to use a .tflite model following your instructions.
When I run de project i get the following error:
Error: The package 'react-native-fast-tflite' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo Go

at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:203:6 in guardedLoadModule
at http://192.168.1.17:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:297699:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:370:8 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:113:4 in callFunctionReturnFlushedQueue

› Opening on Android...
› Opening exp://192.168.1.17:19000 on 22041216G
› Press ? │ show all commands
› Opening on Android...
› Opening exp://192.168.1.17:19000 on 22041216G
› Press ? │ show all commands
Android Bundling complete 74ms
Android Running app on 22041216G

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:370:8 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:113:4 in callFunctionReturnFlushedQueue

Error: The package 'react-native-fast-tflite' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo Go

at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:203:6 in guardedLoadModule
at http://192.168.1.17:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:297699:3 in global code

Can you please help on this issue?
Regards.

**Comment by mrousavy** [comment]
I don't know, I didn't create that example.
Maybe try creating a new app instead of modifying that example.

Or try my example here.

**Comment by jcverah** [comment]
Hello,
The example works ok with a non tflite model. I just added your lib and try
to open a tflite model.
I see the error appearing when trying to open the model. Otherwise no
errors.
Do you know if the model can generate this error? I have verified that
model on py and it works perfectly
Thank you very much

**Comment by ElMahdiAboulmanadel** [comment]
I have the same exact problem. Please answer
