### ISSUE TITLE
result classes only shows array of numbers [TFLite}

### ISSUE THREAD

**Issue by notaltt** [mrousavy/react-native-fast-tflite#54]
I am currently using TFLite to load my model.tflite and I am trying to get the name of the classes that detected by the Camera. But, the problem is it only shows the number of arrays. Any suggestions for me to solve my problem?

Dependencies:
![image](https://github.com/mrousavy/react-native-fast-tflite/assets/88723385/a06792b3-b77c-4d5d-a283-ad40664632c2)

Code in my FrameProcessor:
![image](https://github.com/mrousavy/react-native-fast-tflite/assets/88723385/609da0f2-6cb2-4d6f-bf6a-c36f30b66a76)

model.tflite - I don't have labels.txt cause this is from the kaggle and it didn't provide any..
![image](https://github.com/mrousavy/react-native-fast-tflite/assets/88723385/f09fbf0a-6079-4894-9401-0ce517460aa3)

**Comment by mrousavy** [comment]
This is how TFLite works.

You input arrays of numbers, it outputs arrays of numbers.

The model description even shows you that there are 4 output arrays, the second one is categories and the third one is scores.

You need to look those up with the labels.txt file, so you need that file. This is how TFLite works.
