### ISSUE TITLE
Require statement not part of import statement.eslint@typescript-eslint/no-var-requires

### ISSUE THREAD

**Issue by anz-ryu** [mrousavy/react-native-fast-tflite#57]
I tried:

- `import my_tflite_model from "../../../assets/MyDetection.tflite";`
  - ERROR:  Cannot find module '../../../assets/MyDetection.tflite' or its corresponding type declarations.
- `import my_tflite_model = require("../../../assets/MyDetection.tflite");`
  - ERROR:  Cannot find module '../../../assets/MyDetection.tflite' or its corresponding type declarations.
- `const my_tflite_model = require("../../../assets/MyDetection.tflite");`
  - ERROR:  Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)
- `const my_tflite_model = useTensorflowModel(require("../../../assets/MyDetection.tflite"));`
  - ERROR:  Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)
  - ERROR: React Hook "useTensorflowModel" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function.eslint[react-hooks/rules-of-hooks](https://reactjs.org/docs/hooks-rules.html)
- `const my_tflite_model = loadTensorflowModel(require("../../../assets/MyDetection.tflite"));`
  - ERROR: Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)

Before that, I did:

1. `yarn add react-native-fast-tflite`
2. Add `tflite` to `module.exports. resolver. assetExts` in `metro.config.js`.
3. Add `MyDetection.tflite` to the `../../../assets` folder.

Em,
How can I use this library? (I just want to create a function that can run my model.)

**Comment by mrousavy** [comment]
> const my_tflite_model = require("../../../assets/MyDetection.tflite");
> ERROR: Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)

This is a **lint error**, not an actual **code error**, meaning it goes against your preferred code-style rules. You can disable that for this case, because it needs to be a `require`.
