### ISSUE TITLE
How can I use this with expo?

### ISSUE THREAD

**Issue by kenhuang1964** [mrousavy/react-native-fast-tflite#6]
Hey guys, I am using expo and I'm having some trouble following this step which only works for vanilla react native:
![image](https://github.com/mrousavy/react-native-fast-tflite/assets/87556616/dcfcae77-ec2e-4a37-b30e-6bcc5318897e)

**Comment by gasparitiago** [comment]
Hey @kenhuang1964 , how did you solve this problem?

**Comment by kenhuang1964** [comment]
Hey @gasparitiago, I was able to get the metro.config.js file, but I didn't end up using this library

**Comment by mrousavy** [comment]
This _could_ be built with a expo-config-plugin

**Comment by antun** [comment]
@gasparitiago can I ask which library you ended up using?

**Comment by TowhidKashem** [comment]
@mrousavy Hey Mark! i don't have the metro issue since my expo project already uses one but can u tell me if the GPU acceleration can be done in expo? I know how to do this part using a config plugin:

https://github.com/mrousavy/react-native-fast-tflite?tab=readme-ov-file#using-gpu-delegates

but what about the xcode part, I never had to open it for my project so not sure if it's doable. Much thanks!

**Comment by mrousavy** [comment]
Hey - I am not sure, I haven't used this lib in an expo project yet. But I would really appreciate it if you guys would figure out how to create an expo config plugin for both the CoreML delegate as well as the babel mods! 🙏

**Comment by TowhidKashem** [comment]
> Hey - I am not sure, I haven't used this lib in an expo project yet. But I would really appreciate it if you guys would figure out how to create an expo config plugin for both the CoreML delegate as well as the babel mods! 🙏 

Gotcha, I ended up moving to an endpoint hosted model but prior to that had written the config plugin to add the core ml delegate entry to the pod file. Gonna leave it here in case it helps:

`const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');
const {
  insertContentsAtOffset
} = require('@expo/config-plugins/build/utils/commonCodeMod');

module.exports = function withCoreMLDelegate(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile'
      );

      const podfileContents = fs.readFileSync(podfilePath, 'utf-8');

      const newPodfileContents = insertContentsAtOffset(
        podfileContents,
        [
          '# [mod]: enable GPU acceleration for on-device ML',
          '$EnableCoreMLDelegate = true',
          ''
        ].join('\n'),
        0
      );

      fs.writeFileSync(podfilePath, newPodfileContents);

      return config;
    }
  ]);
};`

**Comment by mrousavy** [comment]
Thanks @TowhidKashem!! :)

1. I'll use that for reference for the expo-config-plugin sometime in the future - thanks!!
2. Yea, whoops lol I meant metro not babel! So there's no mods for that, the user has to add it themselves? Got it!
