### ISSUE TITLE
Support on TypeScrip

### ISSUE THREAD

**Issue by nathangabriel27** [mrousavy/react-native-fast-tflite#66]
Is there any TS method that I can import and define in my variables?

![image](https://github.com/mrousavy/react-native-fast-tflite/assets/43018177/8e0b6eac-7c28-45e8-948b-d0e419ce5ceb)

I'm trying to use a useSharedValue in react-native-reanimated, but when setting the TS to const I can't use it with any import from the library.
![image](https://github.com/mrousavy/react-native-fast-tflite/assets/43018177/a865de2c-e93a-414f-88ae-1a59e68c3c8e)

Is there any "TypedArrayProps" for example?

**Comment by mrousavy** [comment]
It's `ArrayBuffer`. Or `Uint8Array` if you prefer to type it with a view.
