### ISSUE TITLE
error: SyntaxError: ...\assets\model\model.tflite: Unexpected character '∟'. (1:0)

### ISSUE THREAD

**Issue by bigg-S** [mrousavy/react-native-fast-tflite#68]
I'm experiencing an issue with loading a TensorFlow Lite model in my React Native project. When attempting to load the model, I receive a syntax error indicating unexpected characters in the model binary string. It seems the model file is being read as text rather than binary. I suspect this is causing the error, but I'm unsure how to correctly handle the binary file in React Native. Any guidance on properly loading a TensorFlow Lite model in React Native would be greatly appreciated.

This is the error am getting,
"
error: SyntaxError: \assets\model\model.tflite: Unexpected character '∟'. (1:0)

> 1 | ∟TFL3¶ ∟↑¶►♦¶∟�,☺D��T��hk�♥☺♦j"[�♀∟h☼serving_default☻,♦L����☺♦►detection_scoresp����☺♦☼detection_boxes☺♦B@[�♦♠inputs♥X(♦�����☺♦☼TFLITE_METADATA�����☺♦‼CONVERSION_METADAT�☺♦‼min_runtime_version�☺¶��♀��|��칤\��̶�|��,��ܯ����|��l��\��L��<��,��∟��♀�����삤�|��v��p��j��a��X�|O�lF�\=�L4�<%�,▬�∟�♀�����٣�ף�գ�ӣ�ѣ�ϣ�ͣ|ˣlɣ\ǣLţ<ã,��∟��♀�����츣ܶ�̴�������������|��l��\��L��<��,��∟��♀�����엣ܕ�̓�������������|��l��\��L��<���|�∟|��{�<n��l�<l��W�|W�,C��B��'��&��♂�\♂�L        �<�,��∟��♀���⌂��~��H��G��◄�,►�∟�����|l��j��h��↨�<§�,������♦��☺��z��u��s��q��o�♀o��n�a��X��@��∟�������z��2��ҝpr�`↕�P���������o��☼��O�pϙ`O�Pϖ@O�0ϓ O�►ϐ���.��·�n��♫�0
    | ^
  2 | � M�►�|Mw��m��d�,[��Q�lH�gH��5��5p"3`►3P►2@�10�0 �0►�/�/��.��.��-��-��,��,��+��+p�*`⌂*P⌂)@m)0%) %(►%'%&�$%�$$�$#�$"�$!�$ �$▼�$▲p$↔`$∟P$$→0$↓ ↕↓►↕↑↑��▬��▬��§��§��¶��‼��↕��◄p�►`�☼P�♫@�
  3 | 0�♀ �♂►�
  4 | � �����♠��♣��♦��♦��♦��♦p�♦`�♦P�♦4�♦↑�♦�♦�♦��♦؉♦Љ♦ȉ♦��♦��♦��♦��♦��♦��♦��♦��♦��♦x�♦p�♦h�♦`�♦X�♦P�♦H�♦@�♦8�♦0�♦(�♦ �↑�♦►��♦�♦��♦��♦�♦��♦؈♦Ј♦Ȉ♦��♦��♦��♦��♦��♦��♦��♦��♦��♦x�♦p�♦h�♦`�♦X�♦P�♦H�♦@�♦8�♦0�♦(�♦ �♦↑�♦►��♦�♦��♦��♦�♦��♦؇♦Ї♦ȇ♦��♦��♦��♦��♦��♦��♦��♦��♦��♦x�♦p�♦h�♦`�♦X�♦P�♦H�♦@�♦8�♦0�♦(�♦ �♦↑�♦►��♦�♦��♦��♦�♦��♦؆♦І♦Ȇ♦��♦��♦��♦��♦��♦��♦��♦��♦��♦x�♦p�♦h�♦`�♦X�♦P�♦H�♦@�♦8�♦0�♦(�♦ �♦↑�♦►��♦�♦��♦��♦�♦��♦؅♦Ѕ♦ȅ♦��♦��♦��♦��♦��♦��♦��♦��♦��♦x�♦p�♦h�♦`�♦X�♦P�♦H�♦@�♦8�♦0�♦(�♦ �♦↑�♦�♦�♦��♦��♦�♦��♦؄♦Є♦Ȅ♦��♦��♦��♦��♦��♦��♦��♦��♦��♦x�♦p�♦h�♦`�♦X�♦P�♦H�♦@�♦8�♦0�♦(�♦ �♦↑�♦►��♦�♦��♦��♦�♦��♦؃♦Ѓ♦ȃ♦��♦��♦��♦��♦,�♦♦�G[�♦↑�♦∟M001¶¶►♦¶►↑D�♦؂♦♣1.5.0☺∟↑►♦↑♀�⌂♦(�♦☺♦|~�t⌂♦l⌂♦¶V001
  "
  
  This is the code sample,
  "
  import React, { useEffect, useState } from "react";
import { SafeAreaView, View, Text, TouchableOpacity, Image, Platform } from "react-native";
import { RNCamera } from "react-native-camera";
import { useNavigation } from "@react-navigation/native";
import Icon from "react-native-vector-icons/MaterialIcons";
import FlashModeService from "@utils/camera/FlashModeService";
import CameraService from "@utils/camera/CameraService";
import useCamera from "@hooks/camera/useCamera";
import useCallbackRef from "@hooks/camera/useCallbackRef";
import styles from "../../styles";

import * as tf from "@tensorflow/tfjs";
import { cameraWithTensors } from "@tensorflow/tfjs-react-native";
import { TensorflowModel, loadTensorflowModel } from "react-native-fast-tflite";

const pitchTemplate = require("../assets/pitch-template/pitch_template.png");

// camera with tensor
const TensorCamera = cameraWithTensors(RNCamera);

const flashModeService = new FlashModeService();
const cameraService = new CameraService();

const Camera = () => {
	const navigation = useNavigation();
	const [flashMode, setFlashMode] = useState(RNCamera.Constants.FlashMode.off);
	const [cameraType, setCameraType] = useState(RNCamera.Constants.Type.back);
	const { ref, callbackRef } = useCallbackRef();

	const [hasPermission, setHasPermission] = useState<null | boolean>(null);
	const [model, setModel] = useState<TensorflowModel>();

	const [ready, setReady] = useState(false);

	const { seconds, recording, startRecordingVideo, stopRecordingVideo } = useCamera(ref);

	const [pitchTemplateSize, setPitchTemplateSize] = useState({ width: 0, height: 0 });

	const textureDims = Platform.OS === "ios" ?
		{
			height: 1920,
			width: 1080,
		} :
		{
			height: 1200,
			width: 1600,
		};

	const initialiseTensorflow = async () => {
		await tf.ready();
		tf.getBackend();
	};

	const handleCameraLayout = (event: { nativeEvent: { layout: { width: any; height: any; }; }; }) => {
		const { width, height } = event.nativeEvent.layout;
		setPitchTemplateSize({ width, height });
	};

	const onTorchPress = () => {
		setFlashMode(flashModeService.getNewFlashMode(flashMode));
	};

	const changeCameraType = () => {
		setCameraType(cameraService.getNewCameraType(cameraType));
	};

	// confirm pitch alignment
	const makeReady = () => {
		setReady(true);
	};

	const handleCameraStream = (images: IterableIterator<tf.Tensor3D>) => {
		const loop = async () => {
			if (model) {
				const nextImageTensor = images.next().value;
				if (nextImageTensor) {
					const objects = await model.run(nextImageTensor);
					console.log(objects);
					handleObjectDetection(objects);
					tf.dispose([nextImageTensor]);
				}
			}
			requestAnimationFrame(loop);
		};
		loop();
	};

	useEffect(() => {
		(async () => {
			// initialise Tensorflow
			await initialiseTensorflow();
			// load the model
			try {
				const myModel = await loadTensorflowModel(require('../assets/model/model.tflite'), 'default');
				console.log('Model loaded successfully!');
				setModel(myModel);
			} catch(error: any) {
				console.log('An error occurred: ', error);
			}
			

		})();
	}, []);

	const handleObjectDetection = (object: any) => {
		// Check if 'bowlers' are detected
		const detectedBowlers = object.find((object: { label: string; }) => object.label === "bowlers");
		if (detectedBowlers) {
			// Start recording when 'bowlers' are detected
			startRecording();
		}
	};

	const startRecording = () => {
		if (!recording) {
			startRecordingVideo();
			// Automatically stop recording after 4 seconds
			setTimeout(() => {
				stopRecordingVideo();
			}, 4000);
		}
	};

	return (
		<SafeAreaView style={styles.container}>
			<TensorCamera
				ratio={"4:3"}
				style={styles.camera}
				type={cameraType}
				flashMode={flashMode}
				captureAudio={true}
				onReady={() => { handleCameraStream; } }
				resizeHeight={200}
				resizeWidth={152}
				resizeDepth={3}
				autorender={true}
				cameraTextureHeight={textureDims.height}
				cameraTextureWidth={textureDims.width} useCustomShadersToResize={false}			>
				<View style={styles.header}>
					<TouchableOpacity onPress={navigation.goBack}>
						<Icon
							name="close"
							size={24}
							color="#FFF"
							style={styles.closeIcon}
						/>
					</TouchableOpacity>

					{recording && (
						<View style={styles.timer}>
							<Text style={styles.timerText}>Time Remaining</Text>
							<View style={styles.timeContainer}>
								<View style={styles.dot} />
								<Text style={styles.timerText}>00:{seconds}</Text>
							</View>
						</View>
					)}

					{cameraService.isBackCamera(cameraType) && (
						<TouchableOpacity onPress={onTorchPress}>
							<Icon
								name="flash-on"
								size={24}
								color="#FFF"
								style={styles.torchIcon}
							/>
						</TouchableOpacity>
					)}
				</View>

				{!ready && (
					<View style={styles.cameraContainer} onLayout={handleCameraLayout}>
						<Text style={styles.overlayText}>Align the pitch with the template on the screen and press continue</Text>
						<Image
							source={pitchTemplate}
							style={[styles.pitchTemplate, pitchTemplateSize]}
							resizeMode="contain"
						/>
					</View>
				)}

				<View style={styles.captureContainer}>
					<TouchableOpacity
						onPress={makeReady}
					>
						<Text style={styles.footerText}>Continue</Text>
					</TouchableOpacity>
					<TouchableOpacity onPress={changeCameraType} disabled={recording}>
						<Icon
							name="flip-camera-ios"
							size={54}
							color="#FFF"
							style={styles.switchCameraIcon}
						/>
					</TouchableOpacity>
				</View>

			</TensorCamera>
		</SafeAreaView>
	);
};

export default Camera;
"

**Comment by bigg-S** [comment]
I misinterpreted some instructions, I apologize.

**Comment by bishalkc** [comment]
> I misinterpreted some instructions, I apologize.

I am facing same issue, what did you do to fix it?

```
create a model with Vertext and exported as tflite 
model.tflite: Unexpected character ''. (1:0)
```

**Comment by bigg-S** [comment]
I had the issue because I hadn't included this line in my metro.config.js,

> assetExts: ['tflite'
