### ISSUE TITLE
Error: react-native-fast-tflite is not yet supported on Android! I couldn't manage to get TFLite to build for NDK/C++

### ISSUE THREAD

**Issue by t-genc** [mrousavy/react-native-fast-tflite#7]
Hi @mrousavy , I am using expo-49 on android and getting this error

**Comment by mrousavy** [comment]
Yep, as you can read in the title, RN Fast TFLite is not supported on Android yet.

See this section in the README:

<img width="881" alt="Screenshot 2023-09-19 at 10 44 51" src="https://github.com/mrousavy/react-native-fast-tflite/assets/15199031/1594ef44-8593-4eb0-b84f-27d2181143ef">

**Comment by rodgomesc** [comment]
i’ve linked tflite with my shared lib in a personal project a few months ago, tomorrow i’ll try to find it and share that part

**Comment by rodgomesc** [comment]
i was able to get it working on android by just adding some  missing headers and removing those lines from the async thread, didn't have time yet to debug this yet, just pasting in case it's obvious for someone at first glance

```cpp
Buffer buffer = fetchURL(modelPath);
auto model = TfLiteModelCreate(buffer.data, buffer.size);
```


![image](https://github.com/mrousavy/react-native-fast-tflite/assets/4893591/6a7049b1-f14d-4ee7-8098-a40a9abdd0e4)

**Comment by mrousavy** [comment]
Awesome!! How did you include it in CMake?

**Comment by rodgomesc** [comment]
didn't changed anything on cmake just removed the comments you implemented previously

**Comment by rodgomesc** [comment]
i've created this small script to build it and copy the headers, 

```shell
#!/bin/bash

# Variables
output_dir="output"


cd tensorflow || exit 1


rm -rf tmp output
mkdir -p tmp/include
mkdir -p "$output_dir/include"
mkdir -p "$output_dir/lib"


abis="android_arm64=arm64-v8a android_arm=armeabi-v7a android_x86_64=x86_64"


for abi in $abis; do
  rm -rf bazel-bin bazel-out
  IFS="=" read -r key value <<< "$abi"
  output_subdir="$value"

  bazel build \
          -c opt \
          --config="$key" \
          //tensorflow/lite/c:tensorflowlite_c


  mkdir -p "$output_dir/lib/$output_subdir"
  cp bazel-bin/tensorflow/lite/c/libtensorflowlite_c.so "$output_dir/lib/$output_subdir/" || exit 1
done

# include tensorflow headers
rsync -avm --include='*.h' -f 'hide,! */' tensorflow tmp/include


cp -r tmp/include "$output_dir/"
```

i've facing issues in previous projects while building tflite on mac, even if it compiles successfully with symbols in place, so just to make sure i created this docker file also 

```Dockerfile
# Using the latest Ubuntu LTS arm64 image
FROM amd64/ubuntu:22.04

# Define bazel version
ARG BAZEL_VERSION=5.3.0

ENV ANDROID_DEV_HOME /android
RUN mkdir -p ${ANDROID_DEV_HOME}

ENV ANDROID_SDK_FILENAME commandlinetools-linux-9645777_latest.zip
ENV ANDROID_SDK_URL https://dl.google.com/android/repository/${ANDROID_SDK_FILENAME}

ENV ANDROID_API_LEVEL 30
# min API level supported by NDK
ENV ANDROID_NDK_API_LEVEL 23
ENV ANDROID_BUILD_TOOLS_VERSION 30.0.3
ENV ANDROID_SDK_HOME ${ANDROID_DEV_HOME}/sdk
RUN mkdir -p ${ANDROID_SDK_HOME}/cmdline-tools
ENV PATH ${PATH}:${ANDROID_SDK_HOME}/cmdline-tools/latest/bin:${ANDROID_SDK_HOME}/platform-tools
ENV ANDROID_NDK_FILENAME android-ndk-r21e-linux-x86_64.zip
ENV ANDROID_NDK_URL https://dl.google.com/android/repository/${ANDROID_NDK_FILENAME}
ENV ANDROID_NDK_HOME ${ANDROID_DEV_HOME}/ndk
ENV TOOLCHAIN=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64


ENV PATH ${PATH}:${ANDROID_NDK_HOME}:${TOOLCHAIN}/bin


ARG UID=1000


RUN apt-get update -y

RUN apt-get install -y sudo \
      git \
      g++ \
      gdb \
      clang \
      curl \
      python3-numpy \
      gnupg \
      apt-transport-https \
      openjdk-11-jdk \
      make \
      ninja-build \
      cmake \
      autoconf \
      automake \
      libtool \
      locales-all \
      dos2unix \
      rsync \
      tar \
      unzip \
  && apt-get clean



RUN cd ${ANDROID_DEV_HOME} && \
    curl --progress-bar -L -O ${ANDROID_SDK_URL} && \
    unzip ${ANDROID_SDK_FILENAME} -d /tmp && \
    mv /tmp/cmdline-tools ${ANDROID_SDK_HOME}/cmdline-tools/latest && \
    rm ${ANDROID_SDK_FILENAME}



RUN cd ${ANDROID_DEV_HOME} && \
    curl --progress-bar -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" -O ${ANDROID_NDK_URL} && \
    unzip ${ANDROID_NDK_FILENAME} -d ${ANDROID_DEV_HOME} && \
    rm ${ANDROID_NDK_FILENAME} && \
    bash -c "ln -s ${ANDROID_DEV_HOME}/android-ndk-* ${ANDROID_NDK_HOME}"


# make android ndk executable to all users.
RUN chmod -R go=u ${ANDROID_DEV_HOME}

# add build user to sudoers
RUN echo "builder ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/builder


# download and install Bazel
RUN curl -fL --progress-bar -O https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh && \
chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh 

RUN ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh && \
rm -f bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh;


# Set the locale
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8


# create a new user using the provided user id
RUN useradd -m -u ${UID} -s /bin/bash builder

# switch to the new user
USER builder

CMD ["/bin/bash"]

```

and then 

```shell
# build it
docker build . -t builder -f build.DockerFile

# execute on current project dir
docker run -it -v $PWD:/host_dir builder

# build from inside docker 
cd host_dir && ./build_tflite.sh

**Comment by chaitanyaa-simform** [comment]
Hi @rodgomesc , I am also facing the same error while testing this in Android, can you please explain the step-wise solution for script and docker? and how exactly you have used the script for error solving. i am not getting above solution.

**Comment by GZLiew** [comment]
anyone figure this out yet?

**Comment by OneLaddd** [comment]
I really hope you guys could fix this! This would be a great addition

**Comment by frankbaele** [comment]
You can take a look rodgomesc test -> https://github.com/rodgomesc/react-native-fast-tflite
I'm also trying to figure this one out, because this implementation seems very promising compared to other RN tflite implementations.

**Comment by chaitanyaa-simform** [comment]
Does this works for Android ?? I looked at the read me. I think it's the same configaration.

**Comment by frankbaele** [comment]
Im still testing it but the was working on the build -> https://github.com/rodgomesc/react-native-fast-tflite/commit/8fa1476786eceef9e49c9ab9191022842e35e102

**Comment by OneLaddd** [comment]
Did it work? @frankbaele

**Comment by rodgomesc** [comment]
it works i didn't send a pr because is a mess right now, need  time to organize the code and cleanup some things, for what i'm working  i decided to use pure C implementation

**Comment by fazzysyed** [comment]
Does this works for Android now??

**Comment by bfar97** [comment]
I'm also looking forward to seeing this working on android. @rodgomesc tell me if you need any kind of assist on this.

**Comment by c-goettert** [comment]
Would be great to have this on android 👍

**Comment by MuhammadAbdullah54321** [comment]
@rodgomesc it would be awesome to see this working on android as well and thanks for your time

**Comment by rodgomesc** [comment]
Hello everyone,

I apologize for the delay in my response, I've been quite busy lately. I have a proposition that could potentially benefit us all. How about we consider sponsoring @mrousavy with a contribution of $50? This could help in offloading some tasks on his end, and in turn, he might be able to provide me some guidance to solve another issue that's important to me,

What are your thoughts on this?

**Comment by antun** [comment]
@rodgomesc I'd be interested in chipping in $50 to help fund Android support on this project. I'm not sure how we'd go about coordinating. But I see there's a [Discord channel](https://discord.com/channels/1147256486762913884/1147256815474725044) - maybe we can chat about it there?

**Comment by frankbaele** [comment]
same, also willing to chip in

**Comment by jaroslawkrol** [comment]
🎅 **Ho, Ho, Ho! 🎄**

Hey fellow coders and code-esses! 🚀 Guess what? react-native-fast-tflite just got an cool PR #12 ! 🛠️🎁

🎁 **Your turn to spread the cheer:**
Now, I've heard rumors that some of you promised to support Santa (aka me!) for fixing this. 🎅 If you're ready to make good on those promises, drop a line below! Let's make sure the tech elves are accounted for in Santa's nice list! 📜🎉

🎄 **Note:**
This PR is more festive than a tree full of twinkling lights. Take a look, share your thoughts, and let's keep the holiday coding spirit alive! 🎅🎄

🍪 **Cookies for all who contribute! 🍪**

Merry coding and happy holidays to all! 🌟

**Comment by mrousavy** [comment]
[react-native-fast-tflite 1.0.0 is out](https://github.com/mrousavy/react-native-fast-tflite/releases/tag/v1.0.0) and it now supports Android! 🥳🚀

Thanks to @jaroslawkrol for spotting the version mistake in `build.gradle` it now builds fine! 👏
