### ISSUE TITLE
SkRect not defined

### ISSUE THREAD

**Issue by shuffledex** [mrousavy/react-native-fast-tflite#73]
Just for curiosity, i'm trying to replicate the example code but idk what is the library used to draw the rect. I was googling SkRect but I can't find what lib is.

```
const rect = SkRect.Make(left, top, right, bottom)
canvas.drawRect(rect, SkColors.Red)
```

Any help?
Thanks

**Comment by mufaawan** [comment]
@shuffledex I think the library is https://docs.expo.dev/versions/latest/sdk/skia/
