### ISSUE TITLE
Support for Expo Go?

### ISSUE THREAD

**Issue by kenhuang1964** [mrousavy/react-native-fast-tflite#8]
ERROR  Error: The package 'react-native-fast-tflite' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes

Can you please add support for Expo react native?

**Comment by mrousavy** [comment]
This is not supported in Expo Go as the Expo team does not add this library to their Expo Go dev client. You need to use a custom expo dev client.
