### ISSUE TITLE
Error loading model

### ISSUE THREAD

**Issue by gh-pro** [mrousavy/react-native-fast-tflite#9]
Hy, i use plugin but i'm error in app 

error => 
'Failed to load Tensorflow Model 1!', [TypeError: right operand of 'in' is not an object]

=> Platform
real device IOS 17 iphone 14 pro

v. "react-native-fast-tflite": "^0.3.0",
"react-native-vision-camera": "^3.3.1",

**Comment by mrousavy** [comment]
No repro, no logs. Closing

**Comment by gh-pro** [comment]
Sorry has no model, for complete my error in github
