### ISSUE TITLE
fatal error: 'tensorflow/lite/c/c_api.h' file not found

### ISSUE THREAD

**Issue by Pingou** [mrousavy/react-native-fast-tflite#91]
on 1.4.0, I have the following error on mac m2 when compiling:

In file included from /Users/pingou/react/app/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp:9:
/Users/pingou/react/app/node_modules/react-native-fast-tflite/android/../cpp/TensorHelpers.h:15:10: fatal error: 'tensorflow/lite/c/c_api.h' file not found
#include <tensorflow/lite/c/c_api.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by OleksiiZdaly** [comment]
I'm having the same issue.

**Comment by CannoChen** [comment]
Same issue here:
`Execution failed for task ':react-native-fast-tflite:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `E:\project\webstorm\smartBMS\node_modules\react-native-fast-tflite\android\.cxx\Debug\502y674m\arm64-v8a'
  [1/4] Building CXX object CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp.o
  FAILED: CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp.o
  D:\language\Sdk\ndk\26.1.10909125\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android23 --sysroot=D:/language/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DVisionCameraTflite_EXPORTS -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../cpp -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/src/main/cpp -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../tensorflow -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactCommon -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactCommon/callinvoker -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactAndroid/src/main/jni/react/turbomodule -isystem C:/Users/Administrator/.gradle/caches/transforms-3/2d231602b3d6d1780a035663e64178a2/transformed/jetified-react-android-0.74.2-debug/prefab/modules/jsi/include -isystem C:/Users/Administrator/.gradle/caches/transforms-3/2d231602b3d6d1780a035663e64178a2/transformed/jetified-react-android-0.74.2-debug/prefab/modules/reactnativejni/include -isystem C:/Users/Administrator/.gradle/caches/transforms-3/ef7351e37da224f386bf8eb81857fc8c/transformed/jetified-fbjni-0.6.0/prefab/modules/fbjni/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O2 -frtti -fexceptions -Wall -fstack-protector-all -DANDROID -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp.o -MF CMakeFiles\VisionCameraTflite.dir\E_\project\webstorm\smartBMS\node_modules\react-native-fast-tflite\cpp\TensorHelpers.cpp.o.d -o CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp.o -c E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp
  In file included from E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorHelpers.cpp:9:
  E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../cpp/TensorHelpers.h:15:10: fatal error: 'tensorflow/lite/c/c_api.h' file not found
  #include <tensorflow/lite/c/c_api.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [2/4] Building CXX object CMakeFiles/VisionCameraTflite.dir/src/main/cpp/Tflite.cpp.o
  FAILED: CMakeFiles/VisionCameraTflite.dir/src/main/cpp/Tflite.cpp.o
  D:\language\Sdk\ndk\26.1.10909125\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android23 --sysroot=D:/language/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DVisionCameraTflite_EXPORTS -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../cpp -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/src/main/cpp -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../tensorflow -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactCommon -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactCommon/callinvoker -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactAndroid/src/main/jni/react/turbomodule -isystem C:/Users/Administrator/.gradle/caches/transforms-3/2d231602b3d6d1780a035663e64178a2/transformed/jetified-react-android-0.74.2-debug/prefab/modules/jsi/include -isystem C:/Users/Administrator/.gradle/caches/transforms-3/2d231602b3d6d1780a035663e64178a2/transformed/jetified-react-android-0.74.2-debug/prefab/modules/reactnativejni/include -isystem C:/Users/Administrator/.gradle/caches/transforms-3/ef7351e37da224f386bf8eb81857fc8c/transformed/jetified-fbjni-0.6.0/prefab/modules/fbjni/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O2 -frtti -fexceptions -Wall -fstack-protector-all -DANDROID -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/VisionCameraTflite.dir/src/main/cpp/Tflite.cpp.o -MF CMakeFiles\VisionCameraTflite.dir\src\main\cpp\Tflite.cpp.o.d -o CMakeFiles/VisionCameraTflite.dir/src/main/cpp/Tflite.cpp.o -c E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/src/main/cpp/Tflite.cpp
  In file included from E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/src/main/cpp/Tflite.cpp:7:
  E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../cpp/TensorflowPlugin.h:19:10: fatal error: 'tensorflow/lite/c/c_api.h' file not found
  #include <tensorflow/lite/c/c_api.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [3/4] Building CXX object CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorflowPlugin.cpp.o
  FAILED: CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorflowPlugin.cpp.o
  D:\language\Sdk\ndk\26.1.10909125\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android23 --sysroot=D:/language/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DVisionCameraTflite_EXPORTS -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../cpp -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/src/main/cpp -IE:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../tensorflow -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactCommon -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactCommon/callinvoker -IE:/project/webstorm/smartBMS/node_modules/react-native/ReactAndroid/src/main/jni/react/turbomodule -isystem C:/Users/Administrator/.gradle/caches/transforms-3/2d231602b3d6d1780a035663e64178a2/transformed/jetified-react-android-0.74.2-debug/prefab/modules/jsi/include -isystem C:/Users/Administrator/.gradle/caches/transforms-3/2d231602b3d6d1780a035663e64178a2/transformed/jetified-react-android-0.74.2-debug/prefab/modules/reactnativejni/include -isystem C:/Users/Administrator/.gradle/caches/transforms-3/ef7351e37da224f386bf8eb81857fc8c/transformed/jetified-fbjni-0.6.0/prefab/modules/fbjni/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O2 -frtti -fexceptions -Wall -fstack-protector-all -DANDROID -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorflowPlugin.cpp.o -MF CMakeFiles\VisionCameraTflite.dir\E_\project\webstorm\smartBMS\node_modules\react-native-fast-tflite\cpp\TensorflowPlugin.cpp.o.d -o CMakeFiles/VisionCameraTflite.dir/E_/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorflowPlugin.cpp.o -c E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorflowPlugin.cpp
  In file included from E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/cpp/TensorflowPlugin.cpp:9:
  E:/project/webstorm/smartBMS/node_modules/react-native-fast-tflite/android/../cpp/TensorflowPlugin.h:19:10: fatal error: 'tensorflow/lite/c/c_api.h' file not found
  #include <tensorflow/lite/c/c_api.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "D:\\language\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "E:\\project\\webstorm\\smartBMS\\node_modules\\react-native-fast-tflite\\android\\.cxx\\Debug\\502y674m\\arm64-v8a" ^
        VisionCameraTflite
    from E:\project\webstorm\smartBMS\node_modules\react-native-fast-tflite\android`

**Comment by CannoChen** [comment]
Same issue here. Any one have solution?

**Comment by wkbia** [comment]
Same here. Temporary fix is to manually clone [tensorflow](https://github.com/tensorflow/tensorflow/tree/5bc9d26649cca274750ad3625bd93422617eed4b) repo into `node_modules/react-native-fast-tflite/`.
This is removed every time you run `yarn install`, but you can build the app for now.

**Comment by wkbia** [comment]
> Can you elaborate on your solution? Exactly which module of tensorflow is copied in?

Exactly the one i linked.

**Comment by wkbia** [comment]
> By clone tensor flow repo, did you mean the entire repo of tensorflow?

yes, the entire repo.

**Comment by CannoChen** [comment]
> > > Can you elaborate on your solution? Exactly which module of tensorflow is copied in?
> > 
> > 
> > Exactly the one i linked.
> 
> By clone tensor flow repo, did you mean the entire repo of tensorflow?



No, It is not neccessary! The only thing you must do is to copy `tensorflow/lite` dir to `react-native-fast-tflite/cpp`. 

In my project, It work fine! But, I meet other issue again. It can't read my tflite model now!

**Comment by diegomeire** [comment]
For anyone struggling with this, I managed to make it work by doing the following:

1. Cloned react-native-fast-tflite (with --recurse-submodules) inside my app's folder
2. Modified my tsconfig file to:
```
{
  "extends": "expo/tsconfig.base",
  "paths": {
    "react-native-fast-tflite": ["./react-native-fast-tflite/src/index"]
  },
  "compilerOptions": {
    "strict": true
  }
}

```

3. I removed the react-native-fast-tflite from the project `yarn remove react-native-fast-tflite`
4. Added react-native-fast-tflite again but this time pointing to the local version. `yarn add ./react-native-fast-tflite`

Hope it helps

**Comment by manu13008** [comment]
@CannoChen was the next issue related also to this issue ? 
Thanks

**Comment by Pingou** [comment]
> Same here. Temporary fix is to manually clone [tensorflow](https://github.com/tensorflow/tensorflow/tree/5bc9d26649cca274750ad3625bd93422617eed4b) repo into `node_modules/react-native-fast-tflite/`. This is removed every time you run `yarn install`, but you can build the app for now.

have you tried pointing to master in instead of the npm version?
Ex of package.json: "react-native-fast-tflite": "git://github.com/mrousavy/react-native-fast-tflite#master",

**Comment by lucksp** [comment]
Are you seeing this on Android & iOS?

I am seeing only in Android

**Comment by diegomeire** [comment]
This is what I did to solve id:
1- Added the package normally through `yarn add react-native-fast-tflite`
2- Kept a copy of `tensorflow` in the app folder
3- Added a post install script on `package.json` to copy the `tensorflow` folder to `node_modules`:  `"postinstall": "cp -r ./tensorflow ./node_modules/react-native-fast-tflite"`

Now, every time I run `yarn install` or add another package, the `tensorflow` folder is re-copied

**Comment by JamTheDev** [comment]
Same problem here. I hope a solution can be delivered this week . I need TFLite for my project. Thanks

**Comment by manu13008** [comment]
> Same problem here. I hope a solution can be delivered this week . I need TFLite for my project. Thanks

Just take the 1.3.0 version while waiting for the issue to be fixed.

**Comment by CannoChen** [comment]
> Same problem here. I hope a solution can be delivered this week . I need TFLite for my project. Thanks

You can try using tensorflowjs directly. For me, I gave up using this repo. after I used tensorflowjs, my project worked correctly. You can find the code in my project: https://github.com/CannoChen/SmartBMS

**Comment by CannoChen** [comment]
> @CannoChen was the next issue related also to this issue ? Thanks

No, it isn't. In my view, I dont suggest you to use this repo. I suggest that you should use tensorflowjs directly!!! It more simple, and more close to tensorflow_lite model.

**Comment by lucksp** [comment]
> > @CannoChen was the next issue related also to this issue ? Thanks
> 
> No, it isn't. In my view, I dont suggest you to use this repo. I suggest that you should use tensorflowjs directly!!! It more simple, and more close to tensorflow_lite model.

I’d like to try using TFJS directly. But are the docs from tensorflow correct to install in React native?

**Comment by CannoChen** [comment]
> > > @CannoChen was the next issue related also to this issue ? Thanks
> > 
> > 
> > No, it isn't. In my view, I dont suggest you to use this repo. I suggest that you should use tensorflowjs directly!!! It more simple, and more close to tensorflow_lite model.
> 
> I’d like to try using TFJS directly. But are the docs from tensorflow correct to install in React native?

Of course, you can! But there are some tricks that you may focus:

- You must use Tensorflow with version 2.8.

- Please use python with version 2.10

- If you want to have a demo, please read my code in [https://github.com/CannoChen/SmartBMS/tree/main/src/service/slice/TFLiteSlice.ts](https://github.com/CannoChen/SmartBMS/blob/main/src/service/slice/TFLiteSlice.ts)

**Comment by RayanMoarkech** [comment]
I think this issue is related to the file change to `android/CMakeLists.txt`
https://github.com/mrousavy/react-native-fast-tflite/commit/35d7cbdcb25fee51584f0c5667c9764d4f2ffcfe

**Comment by lucksp** [comment]
> This is what I did to solve it: 1- Added the package normally through `yarn add react-native-fast-tflite` 2- Kept a copy of `tensorflow` in the app folder 3- Added a post install script on `package.json` to copy the `tensorflow` folder to `node_modules`: `"postinstall": "cp -r ./tensorflow ./node_modules/react-native-fast-tflite"`
> 
> Now, every time I run `yarn install` or add another package, the `tensorflow` folder is re-copied. This worked for me. Hope it helps

I have tried this suggestion, but the build still fails:

```bash
> Task :react-native-fast-tflite:configureCMakeDebug[arm64-v8a] FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fast-tflite:configureCMakeDebug[arm64-v8a]'.
> [CXX1420] /Users/lucksp/dev/myflyid/node_modules/react-native-fast-tflite/android/CMakeLists.txt debug|arm64-v8a : Could not read '/Users/lucksp/dev/myflyid/node_modules/react-native-fast-tflite/android/.cxx/Debug/271u5e30/arm64-v8a/configure_fingerprint.bin': While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 36s
1047 actionable tasks: 53 executed, 994 up-to-date
Error: /Users/lucksp/dev/myflyid/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: /Users/lucksp/dev/myflyid/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/lucksp/dev/myflyid/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/lucksp/dev/myflyid/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/Users/lucksp/dev/myflyid/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/Users/lucksp/dev/myflyid/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/Users/lucksp/dev/myflyid/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)
```

**Comment by lucksp** [comment]
For those interested, please test https://github.com/mrousavy/react-native-fast-tflite/pull/112 PR posted from @bang9
