### ISSUE TITLE
App freezes when loading tflite model

### ISSUE THREAD

**Issue by feiwu77777** [mrousavy/react-native-fast-tflite#92]
Hello,

The following is my component for taking pictures

```
const CameraContainer = ({ navigation }) => {
  const model = useTensorflowModel(require("../../../../assets/model.tflite"));
  const actualModel = model.state === "loaded" ? model.model : undefined;
```

when I navigate to this component from another component, the app freezes and only render the CameraContainer, once the model is loaded. 

I wanted to ask if there is a workaround that allow me to render the CameraContainer while loading the tflite model?

Thanks

**Comment by mrousavy** [comment]
Yes, move the model to your native app's bundle instead of the JS bundle. Or load it from the web. The `require` is blocking.

**Comment by mweiserdev** [comment]
@mrousavy , how to load from native app's bundle?
