### ISSUE TITLE
App crashing when using frameProcessor

### ISSUE THREAD

**Issue by manu13008** [mrousavy/react-native-fast-tflite#95]
Hi there,
Thanks for this excellent package I look forward to using ! 

I'm struggling with an issue when I set up my frameProcessor. I can see my camera try to show me what it sees and it crashes everytime my react native app running on an Android device.

Am I missing maybe a compatiblity issue ? Or a config issue that I'm not aware ?

Thanks for your help !

`"dependencies": {
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-fast-tflite": "1.3.0",
    "react-native-safe-area-context": "^4.11.0",
    "react-native-screens": "^3.34.0",
    "react-native-vision-camera": "4.5.1",
    "react-native-windows": "^0.75.0",
    "react-native-worklets-core": "^1.3.3",
    "vision-camera-resize-plugin": "^3.1.0"`
    
    
```
import { View, Text, StyleSheet , Image, SafeAreaView, Platform }from 'react-native';
import { React, useState , useEffect } from 'react';
import {useTensorflowModel, loadTensorflowModel} from 'react-native-fast-tflite'
import { useResizePlugin } from 'vision-camera-resize-plugin';
import {  Camera,  useCameraDevice,  useCameraPermission,  useFrameProcessor,} from 'react-native-vision-camera'


function tensorToString(tensor) {
  return `\n  - ${tensor.dataType} ${tensor.name}[${tensor.shape}]`
}


function modelToString(model) {
  return (
    `TFLite Model (${model.delegate}):\n` +
    `- Inputs: ${model.inputs.map(tensorToString).join('')}\n` +
    `- Outputs: ${model.outputs.map(tensorToString).join('')}`
  )
}



function CameraScreen() {

/////////////////////////////////////////////////////////////////////////////////////
  // Camera Autorisation
  const [isReady, setIsReady] = useState(false);
  const { hasPermission, requestPermission } = useCameraPermission()
  const device = useCameraDevice('back')

  useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      console.log('Camera status',status);
      if (status !== 'authorized') {
        await requestPermission();
      }
    })();
  }, []);


/////////////////////////////////////////////////////////////////////////////////////


  // Loading Model
  const model  = useTensorflowModel(require('./android/app/src/main/assets/best_float16.tflite'))//model path
  const actualModel = model.state === 'loaded' ? model.model : undefined
  // const {model2, state2} = loadTensorflowModel({url : 'https://kaggle/input/efficientdet/tflite/lite0-detection-default/1.tflite'})


  useEffect(() => {
    if (actualModel == null || typeof actualModel.runSync !== 'function') {
      console.log('Model not fully loaded or initialized');
      return;
    }
    console.log('Etat modèle',actualModel)
    console.log(`Model loaded! Shape:\n${modelToString(actualModel)}]`)
  }, [actualModel])



  useEffect(() => {
    if (hasPermission && actualModel != null) {
      setIsReady(true);
    }
  }, [hasPermission, actualModel]);



  console.log('Model1', model, actualModel)
  console.log(`Model: ${model.state} (${model.model != null})`)

  const { resize } = useResizePlugin()

  const frameProcessor = useFrameProcessor(
    (frame) => {
      'worklet'
      try {
        if (actualModel == null) {
          console.log('Model not loaded yet');
          return;
        }
        console.log(`Running inference on frame`);
        const resized = resize(frame, {
          scale: {
            width: 320,
            height: 320,
          },
          pixelFormat: 'rgb',
          dataType: 'uint8',
        });
        const result = actualModel.runSync([resized]);
        const num_detections = result[3]?.[0] ?? 0;
        console.log('Result: ' + num_detections);
      } catch (error) {
        console.error('Error in frame processor:', error);
      }
    },
    [actualModel]
  )

  


  return (
    <View style={styles.container}>
      <Text style={styles.text}>Welcome on the second screen!</Text>
      <Image
          source={require('./android/app/src/main/assets/photo.png')}
          style={styles.image}
          resizeMode="contain"
        />
        {isReady && hasPermission && device != null ? (
        <Camera
          device={device}
          style={StyleSheet.absoluteFill}
          isActive={true}
          frameProcessor={frameProcessor}
          pixelFormat="yuv"
        />
      ) : (
        <Text>No Camera available.</Text>
      )}

    </View>
  );
}

export default CameraScreen;
```

**Comment by manu13008** [comment]
Here are some of my logs : 

0-07 20:26:13.380 22617 22669 I BtGatt.ScanManager: msg.what = 5, msg.arg1 = 0(mMiuiControllingType)
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 22941 newDisplayId = 0
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 22942 newDisplayId = 0
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 22943 newDisplayId = 0
10-07 20:26:13.380  1282  1282 E vendor.qti.hardware.perf@2.2-service: Unknown params
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 22949 newDisplayId = 0
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 23042 newDisplayId = 0
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 22944 newDisplayId = 0
10-07 20:26:13.380  6987 26385 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 23029 newDisplayId = 0
10-07 20:26:13.381  6987  7009 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 23010 newDisplayId = 0
10-07 20:26:13.381  6987  7009 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 23028 newDisplayId = 0
10-07 20:26:13.381  6987 21034 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 23025 newDisplayId = 0
10-07 20:26:13.381  6987 21034 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 23023 newDisplayId = 0
10-07 20:26:13.381  6987 21034 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 22975 newDisplayId = 0
10-07 20:26:13.381  6987 21034 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 3 newDisplayId = 0
10-07 20:26:13.381  6987 21034 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 4 newDisplayId = 0
10-07 20:26:13.381  6987 21034 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 5 newDisplayId = 0
10-07 20:26:13.381  6987  7800 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 6 newDisplayId = 0
10-07 20:26:13.381  6987  1867 D TaskStackChangeListeners: onTaskDisplayChanged =  taskId = 7 newDisplayId = 0
10-07 20:26:13.382 12035 12239 I MediaCodec: configure : init video box disabled
10-07 20:26:13.382 12035 12239 I MediaCodec: fps video to display disabled
10-07 20:26:13.382 12035 12239 D MediaCodec: currery video type video/avc
10-07 20:26:13.383  1887  3090 I ActivityManager: Killing 11663:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0a167i575 (adj 915): camera boost
10-07 20:26:13.385  1887  3090 I SmartPower.com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProbackground->died(99798ms) R(process died ) adj=915.
10-07 20:26:13.385  1887  3128 I SmartPower: com.google.android.googlequicksearchbox/99575 state=inactive adj=915 proc size=0 move to -1 process died
10-07 20:26:13.385  1887  3090 D PerfImpl: perfProcessKillBoost: com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0, 11663, 0
10-07 20:26:13.385 12035 12105 E MiuiCameraCoveredManagerImpl: check service failed
10-07 20:26:13.385 12035 12105 E MiuiCameraCoveredManager: SetCoveredPackageName error, the MiuiCameraCoveredManagerService not ready!
10-07 20:26:13.385  1282  1282 E vendor.qti.hardware.perf@2.2-service: Unknown params
10-07 20:26:13.386  1219  1219 I sensors-hal: batch:242, android.sensor.accelerometer/11, period=200000000, max_latency=0
10-07 20:26:13.386  1219  1219 I sensors-hal: set_config:63, sample_period_ns is adjusted to 200000000 based on min/max delay_ns
10-07 20:26:13.386  1219  1219 I sensors-hal: send_sync_sensor_request:364, send sync request
10-07 20:26:13.386  1219  1219 I sensors-hal: send_sync_sensor_request:390, wait for notification of response
10-07 20:26:13.386 12035 12239 D MediaImpl: MediaImpl::sendFrameRate: 30
10-07 20:26:13.386 12035 12239 D MediaImpl: MediaImpl::sendPackageName: com.awesomeprojectnoexpo
10-07 20:26:13.386 12035 12239 D MediaStub: MediaStub::sendPackageName com.awesomeprojectnoexpo
10-07 20:26:13.386  1887  3090 I ActivityManager: Killing 10353:com.google.process.gapps/u0a163 (adj 955): camera boost
10-07 20:26:13.387  1908 17168 D CameraService: CameraPerf: getpriority success, tid is 17168, priority is 0
10-07 20:26:13.387  1908 17168 D CameraService: CameraPerf: setpriority success, tid is 17168, priority is -10
10-07 20:26:13.387  1908 17168 I CameraService: CameraService::connect call (PID -1 "com.awesomeprojectnoexpo", camera ID 0) and Camera API version 2
10-07 20:26:13.387  1219 12241 I sensors-hal: ssc_conn_resp_cb:689, resp_value = 0
10-07 20:26:13.387  1219  1219 I sensors-hal: send_sync_sensor_request:396, takes 1 ms to receive the response with 0
10-07 20:26:13.387  1219  1219 I sensors-hal: batch:251, android.sensor.accelerometer/11, period=200000000, max_latency=0 request completed
10-07 20:26:13.388  1887  3090 I SmartPower.com.google.process.gapps/10163(10353): background->died(192922ms) R(process died ) adj=955.
10-07 20:26:13.388  1908 17168 V CameraStub: waitFaceAuthenticated:101
10-07 20:26:13.388  1887  3090 D PerfImpl: perfProcessKillBoost: com.google.process.gapps, 10353, 0
10-07 20:26:13.389  1908 17168 V CameraStub: adjCameraPriority:121
10-07 20:26:13.389  1908 17168 I Camera2ClientBase: Camera 0: Opened. Client: com.awesomeprojectnoexpo (PID 12035, UID 10523)
10-07 20:26:13.389  1908 17168 V CameraStub: setClientPackageName:55
10-07 20:26:13.389  1908 17168 D CameraImpl: setClientPackageName:99 com.awesomeprojectnoexpo api2
10-07 20:26:13.389  1908 17168 I CameraDeviceClient: CameraDeviceClient 0: Opened
10-07 20:26:13.389  1282  1282 E vendor.qti.hardware.perf@2.2-service: Unknown params
10-07 20:26:13.391  1887  3090 I ActivityManager: Killing 10263:com.android.providers.calendar/u0a61 (adj 965): camera boost
10-07 20:26:13.392  1908 17168 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0
10-07 20:26:13.393 12035 12095 E CameraManagerGlobal: Camera 4 is not available. Ignore physical camera status change
10-07 20:26:13.393 12035 12095 E CameraManagerGlobal: Camera 5 is not available. Ignore physical camera status change
10-07 20:26:13.393 12035 12095 E CameraManagerGlobal: Camera 6 is not available. Ignore physical camera status change
10-07 20:26:13.394  7242  8935 E CameraManagerGlobal: Camera 4 is not available. Ignore physical camera status change
10-07 20:26:13.394  1887  3090 I SmartPower.com.android.providers.calendar/10061(10263): background->died(193107ms) R(process died ) adj=965.
10-07 20:26:13.394  3989  4250 D FlashlightController: TorchCallback: onTorchModeUnavailable
10-07 20:26:13.394  1887  3128 I SmartPower: com.android.providers.calendar/10061 state=inactive adj=965 proc size=1 move to died process died
10-07 20:26:13.394  7242 21002 E CameraManagerGlobal: Camera 5 is not available. Ignore physical camera status change
10-07 20:26:13.394  1887  3090 D PerfImpl: perfProcessKillBoost: com.android.providers.calendar, 10263, 0
10-07 20:26:13.394  7242 21002 E CameraManagerGlobal: Camera 6 is not available. Ignore physical camera status change
10-07 20:26:13.394  1887  1887 W VibratorManagerServiceImpl: onCameraUnavailable with id0
10-07 20:26:13.395  7242  7242 I BeautyService: onCameraUnavailable:0
10-07 20:26:13.395  1282  1282 E vendor.qti.hardware.perf@2.2-service: Unknown params
10-07 20:26:13.395 12035 12097 I CameraDevices: Camera #0 is now unavailable.
10-07 20:26:13.397  1887  7072 D PerfImpl: perfWarmLaunchBoost: com.google.android.permissioncontroller, -1, 1
10-07 20:26:13.398  1282  1282 E vendor.qti.hardware.perf@2.2-service: Unknown params
10-07 20:26:13.398  1282  1349 E ANDR-PERF-OPTSHANDLER: Min bounds check failed
10-07 20:26:13.398  1282  1349 E ANDR-PERF-OPTSHANDLER: Error! Perflock failed, invalid request value 255
10-07 20:26:13.398  1282  1349 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [12, 6]
10-07 20:26:13.399  1887  7072 D PerfImpl: perfColdLaunchBoost: com.google.android.permissioncontroller, 32397, 102
10-07 20:26:13.400  1282  1282 E vendor.qti.hardware.perf@2.2-service: Unknown params
10-07 20:26:13.400  1887  7072 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (3194607887)
10-07 20:26:13.401  1282  1350 E ANDR-PERF-LM: MetaMeter: handleAsync() 166: AdaptLaunch Invalid Async
10-07 20:26:13.404  1190  2472 I ExtendHAL: [HAL ] ExtendHal3Device.cpp:89 initialize()E cameraId: 0, m_bPassthroughMode: 0
10-07 20:26:13.407 22617 22669 I BtGatt.ScanManager: msg.what = 8, msg.arg1 = 0(mMiuiControllingType)
10-07 20:26:13.407  1887  7072 D IS_CTS_MODE: false
10-07 20:26:13.407  1887  7072 D MULTI_WINDOW_SWITCH_ENABLED: false
10-07 20:26:13.407  1887  7072 D IS_CTS_MODE: false
10-07 20:26:13.407  1887  7072 D MULTI_WINDOW_SWITCH_ENABLED: false
10-07 20:26:13.407  1887  7072 D WindowManager: Input focus has changed to null display=0 updateInputWindows = true
10-07 20:26:13.408  1887  7072 D IS_CTS_MODE: false
10-07 20:26:13.408  1887  7072 D MULTI_WINDOW_SWITCH_ENABLED: false
10-07 20:26:13.408  1887  7072 D IS_CTS_MODE: false
10-07 20:26:13.408  1887  7072 D MULTI_WINDOW_SWITCH_ENABLED: false
10-07 20:26:13.410  6987  6987 W Launcher: onDisplayChanged: newRotation=0, mCurrentRotation=0
10-07 20:26:13.410  3984  4561 D FiveGPowerController: onDisplayChanged to STATE ON
10-07 20:26:13.410  3984  4561 D FiveGPowerController: onDisplayChanged isLastScreenOn is still on,ignore current displayChanged!!!
10-07 20:26:13.411 12035 12035 D DeferrableSurface: New surface in use[total_surfaces=9, used_surfaces=4](androidx.camera.core.processing.SurfaceEdge$SettableSurface@24bff1c}
10-07 20:26:13.411 22617 22669 I BtGatt.ScanManager: msg.what = 5, msg.arg1 = 0(mMiuiControllingType)
10-07 20:26:13.413  3989  3989 V AutoDensityController: on display changed 0 context dpi:449 origin dpi:440 target dpi:449
10-07 20:26:13.414 12035 12035 D DeferrableSurface: use count+1, useCount=1 androidx.camera.core.processing.SurfaceEdge$SettableSurface@24bff1c
10-07 20:26:13.415  3989  4621 D ScreenDecorations: updateOrientation: false
10-07 20:26:13.415 12035 12035 D CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
10-07 20:26:13.416  1190  2472 E CamX    : [ERROR][STATS_AEC] camxcaecstatsprocessor.cpp:5898 SetupStaticNCSLinkForSensor() CAECLight: Unable to Query caps sensor type 7 error CamxResultEFailed
10-07 20:26:13.416  1190  2472 E CamX    : [ERROR][STATS_AEC] camxcaecstatsprocessor.cpp:5898 SetupStaticNCSLinkForSensor() CAECLight: Unable to Query caps sensor type 8 error CamxResultEFailed
10-07 20:26:13.416  1190  2472 E CamX    : [ERROR][STATS_AEC] camxcaecstatsprocessor.cpp:5898 SetupStaticNCSLinkForSensor() CAECLight: Unable to Query caps sensor type 9 error CamxResultEFailed
10-07 20:26:13.416  1190  2472 E CamX    : [ERROR][STATS_AEC] camxcaecstatsprocessor.cpp:5960 SetupStaticNCSLinkForLightSensor() CAECLight: Unable to Query caps sensor type 11 error CamxResultEFailed
10-07 20:26:13.417  1887  2209 D IS_CTS_MODE: false
10-07 20:26:13.417 12035 12035 D CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppos

**Comment by manu13008** [comment]
Actually found the bug.
I forgot to update my babel.config.js file with the command :  


```
plugins: [
    ["react-native-worklets-core/plugin"],
  ]
```

**Comment by mrousavy** [comment]
Nice 👍
